name: JS Checks

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  run-checks-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hemilabs/actions/setup-node-env@v1
      - run: npm run --if-present ci-check
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hemilabs/actions/setup-node-env@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run --if-present --include-workspace-root --workspaces test
    strategy:
      matrix:
        node-version:
          - "20"
          - "22"
          - "24"
